# Generated by Django 4.2.3 on 2024-05-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_expert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interaction',
            table='chicken_expert_app_interaction',
        ),
    ]
